### ISSUE TITLE
open source list

### ISSUE THREAD

**Issue by llllllllll** [quantopian/libpy#114]
## before open sourcing
- [x] documentation
  - [x] install guide
  - [x] tutorial
    - [x] bind scalar function
    - [x] exceptions
    - [x] 1d array input
    - [x] ndarray input
    - [x] ndarray output
    - [x] autoclass
  - [x] prose docs for high level concepts
  - [x] appendix
- [x] rename `scoped_ref` to `owned_ref` to better match CPython terms
- [x] public ci
- [x] don't vendor hash algorithm #135 
- [x] fix python 3.7 and greater
- [x] automodule #121 
- [x] drop py2 https://github.com/quantopian/libpy/issues/148

## after open sourcing
- [x] pypi
- [ ] conda?
- [ ] [Lint Checks for API/ABI Breaks](https://lvc.github.io/abi-compliance-checker/)

**Comment by gerrymanoim** [comment]
We did it!
